# Generated by Django 5.0.1 on 2024-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'Обычный пользователь'), ('MANAGER', 'Менеджер/персонал')], default='USER', max_length=25, null=True, verbose_name='Роль'),
        ),
    ]
